// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AlsoCloud.Marketplace")>]
[<assembly: AssemblyProductAttribute("AlsoCloud.Marketplace")>]
[<assembly: AssemblyDescriptionAttribute("ACMP API")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AlsoCloud.Marketplace"
    let [<Literal>] AssemblyProduct = "AlsoCloud.Marketplace"
    let [<Literal>] AssemblyDescription = "ACMP API"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
